apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  template:
    spec:
      nodeClassRef:
        name: default

      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]

        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m"]

        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["3"]

  # Replace ttlAfterEmpty with expireAfter for v1beta1 NodePool
  expireAfter: 60s

  limits:
    cpu: "200"

  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 60s
