apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: fintech

  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.110.2
    helm:
      values: |
        mode: deployment

        image:
          repository: otel/opentelemetry-collector-contrib

        service:
          type: ClusterIP

        ports:
          otlp:
            enabled: true
            containerPort: 4317
            servicePort: 4317
            protocol: TCP
          otlp-http:
            enabled: true
            containerPort: 4318
            servicePort: 4318
            protocol: TCP

        config:
          receivers:
            otlp:
              protocols:
                grpc: {}
                http: {}

          processors:
            batch: {}

          exporters:
            otlp/jaeger:
              endpoint: "jaeger-collector.observability.svc.cluster.local:4317"
              tls:
                insecure: true

          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlp/jaeger]

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
