apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail-prod
  namespace: argocd
spec:
  project: fintech

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-prod

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: 6.16.6
      helm:
        releaseName: promtail-prod
        valueFiles:
          - $values/fintech-gitops/observability/logging/promtail/values-prod.yaml
    - repoURL: https://github.com/quasar0x/fintech-platform-infra.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
