apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-dev
  namespace: argocd
spec:
  project: fintech

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-dev

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.16.0
      helm:
        releaseName: loki-dev
        valueFiles:
          - $values/fintech-gitops/observability/logging/loki/values-dev.yaml
    - repoURL: https://github.com/quasar0x/fintech-platform-infra.git
      targetRevision: develop
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
