---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-service-secret
  namespace: fintech-prod
spec:
  encryptedData:
    DB_PASSWORD: AgCZ4GbKfmAP5F/ixZynDdj4zwZsuP3f1Q3/rAi2aXSwr9jcpnVgiY0eoM91TA9DAkXIXtnFnCZdAomI4B/BRi3Xkqc7dxhefl3PSN8UWFVa+BFbJ0BxCmXEt0tAiUbkhXjFdziK5z7fEib+9nbQJox+H+ecjgG1wk2Y0n4mGqfcPIZXWvet7nJJyQm3pCoY9h/ub6sshcPsHRbbusenMHGmv2R81UzjDsdzuaQjHf0XT0GTBQFSl4LqaydtmfI0MRCvWg2V9fChNZSkZ1sKOCdts/h75OeuOTVY0Yzb72dOG6aiV/TF6a06ZYo9ivi+UJvqu8Fegfo4TaNjUWpPqM4PyOJxQXEpr2rVPAv5TB3509rmtcmdi9lR+3MJKYUbTNJSrsmMZYMsKfvF8irqO6/FY0mpcwHUXjoPoTosG/MMGb0dXhZt53CMWS1PTaES84/BVH/6imCySD52AloX1O7utGCmRtJPNzCAJywnEr6ujwGnovymImWf9WVzpQAoXxUBJnav96Ldlfj40pqt/RWNQYW+7vmxl8A+2cp6IrZBOWkhZc/fcSkz9rqdcxGTKb6nDO9dHSEpE0Sum5NLNrpGMZ/xu4twyM2h+bT0jXWtpjo2+uaJpfRXGrONslTJP8DH4eNBleIT28oZlcij5XXlUVxcwB3HmzVsFwSL1+tXl/ORdJ190Nowh4QkB7oa5qwqU5xPU+mksBCFkv01UIycpjKFPPCO1Jo=
  template:
    metadata:
      name: user-service-secret
      namespace: fintech-prod
