apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fintech-dev-secrets
  namespace: argocd
spec:
  project: fintech
  destination:
    server: https://kubernetes.default.svc
    namespace: fintech-dev
  source:
    repoURL: https://github.com/quasar0x/fintech-platform-infra.git
    targetRevision: develop
    path: fintech-gitops/apps/dev/secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
