apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fintech
  namespace: argocd
spec:
  description: Fintech GitOps project (dev + prod)

  # Git repos ArgoCD apps are allowed to pull from
  sourceRepos:
    - https://github.com/quasar0x/fintech-platform-infra.git
    - https://grafana.github.io/helm-charts
    - https://prometheus-community.github.io/helm-charts

  # Clusters/namespaces apps are allowed to deploy into
  destinations:
    # prod
    - server: https://kubernetes.default.svc
      namespace: fintech-prod

    # dev
    - server: https://kubernetes.default.svc
      namespace: fintech-dev

    # Argo itself (root apps live here)
    - server: https://kubernetes.default.svc
      namespace: argocd

    - server: https://kubernetes.default.svc
      namespace: monitoring-dev

    - server: https://kubernetes.default.svc
      namespace: monitoring-prod

  # Allow deploying any namespaced resources (safe default for internal projects)
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
