apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
spec:
  project: fintech

  source:
    repoURL: https://github.com/quasar0x/fintech-platform-infra.git
    targetRevision: main
    path: fintech-gitops/charts/fintech-service
    helm:
      valueFiles:
        - ../../apps/prod/values/api-gateway.yaml
        - ../../apps/prod/values/api-gateway.secrets.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: fintech-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
