apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fintech-root
  namespace: argocd
spec:
  project: fintech

  source:
    repoURL: REPO_URL
    targetRevision: main
    path: apps/prod/apps
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
